version: 2
jobs:
  test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Update Rust
          command: |
            sudo apt update
            sudo apt install -y build-essential cmake pkg-config libssl-dev openssl git clang libclang-dev
            ./scripts/init.sh
            rustc --version
            cargo --version
            rustup --version
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "./Cargo.lock" }}
      - run:
          name: Build node
          command: cargo build
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - ./target/debug
          key: cargo-{{ arch }}-{{ checksum "./Cargo.lock" }}
      - run:
          name: Run tests
          command: cargo test

workflows:
  version: 2
  test:
    jobs:
      - test
